### ISSUE TITLE
UX Discussion: Maintaining a tree structure for output datasets

### ISSUE THREAD

**Issue by rwegener2** [ICESat2-SlideRule/h5coro#12]
## Summary

I wonder if it would be more intuitive for the return structures from `readDatasets()` and `listGroups()` which maintained the hierarchical structure of the HDF5 file. This question is related to the idea that perhaps we want separate structures for Groups and Datasets in h5coro which could be tunneled into.

The pro of the tree-like approach would be the ability to dive into the data to the part you want and not have 
to remember where you came from. The pro of the flat approach is that it seems easier for someone to access random 
parts from across the file.

## Details

As a user, returns from `readDatasets()` and `listGroups()` feel flat, something like this:
```
├── \gt1l\heights\h_ph
├── \gt1l\heights\signal_conf_ph
├── \ancillary_data\control
├── \ancillary_data\end_orbit
└── \gt3r\bckgnd_atlas
```

In my brain the internal structure of the data is more of a tree, like this:
```
├── \gt1l\heights
⎸            ├─ h_ph
⎸            └─ signal_conf_ph
├── \ancillary_data
⎸            ├─ control
⎸            └─ end_orbit
└── \gt3r\bckgnd_atlas
```

For me the flat approach has made it harder to keep track of where I am, because I have to do all the management 
of creating paths using `os.path.join()` calls and referencing my next path from the top of the tree.

As an example, accessing the coordinate from a the current output of `listGroups` looks like:

```python
variables['/gt1l/heights/signal_conf_ph']['attributes']['/gt1l/heights/signal_conf_ph/coordinates'].values
```

What about if it were:
```python
h5file['gt1l']['heights']['signal_conf_ph']['attributes']['coordinates'].values
# or 
h5file['gt1l/heights/signal_conf_ph']['attributes']['coordinates'].values
```
These examples had a dictionary-like feeling. Another option would be to model off other [tree libraries](https://treelib.readthedocs.io/en/latest/) in Python, although I don't know a lot about those. Either option, I think, would provoke  the question of "should variables and containers have separate data structures in h5coro?". I think the answer to this at a high level should also be "yes", but there are some more details to hash out there.

**Comment by jpswinski** [comment]
* Accessing an attribute has been fixed and no longer requires the double use of the full path
* The full path to a dataset has been removed from the results when it is provided (and therefore implied) by the original API call
* There is now an H5View class that provides a dictionary overlay to the flattened results - hopefully giving us the best of both worlds; see #15 for more details.
