### ISSUE TITLE
UX Discussion: Returning attributes as their Python type

### ISSUE THREAD

**Issue by rwegener2** [ICESat2-SlideRule/h5coro#13]
Getting back attributes from `variables['/gt1l/heights/h_ph']['attributes']['/gt1l/heights/h_ph/units']` like:
```python
{"elements": 1, "datasize": 7, "numrows": 1, "numcols": 0, "datatype": <class 'str'>, "values": meters}
```
feels to me like perhaps providing more information than is needed. In Python getting the size and class is pretty easy (using `len(string)` or `string.__class__`), so I wonder if we don't need to bend over to provide that information explicitly. `numrows` and 
`numcols` don't mean much to me in this case, but I totally may not be the target user of that info. 

So in the case of attributes, what about having the return from 
`variables['/gt1l/heights/h_ph']['attributes']['/gt1l/heights/h_ph/units']`
just be:
```
meters
```

**Comment by jpswinski** [comment]
2b51387 fixes the readAttribute function.  This issue should now be fully resolved - the data returned for an attribute is just the Python native value.
