### ISSUE TITLE
listGroup with w_inspect set to False does not distinguish between variables and attributes

### ISSUE THREAD

**Issue by rwegener2** [ICESat2-SlideRule/h5coro#20]
## Description

When calling `listGroup` as `h5obj.listGroup(group, w_attr=True, w_inspect=True)` the dictionary that is returned does not distinguish between variables and attributes. This can make it difficult to keep track of which keys are which.  It would be useful if variables and attributes were returned in separate objects.

## Code
```python
from h5coro import h5coro, s3driver
import earthaccess

# getting setup
auth = earthaccess.login()
s3_creds = auth.get_s3_credentials(daac='NSIDC')

my_bucket = 'nsidc-cumulus-prod-protected'
path_to_hdf5_file = 'ATLAS/ATL03/006/2019/11/30/ATL03_20191130112041_09860505_006_01.h5'
# path_to_hdf5_file = 'ATLAS/ATL03/006/2018/10/17/ATL03_20181017222812_02950102_006_02.h5'

h5obj = h5coro.H5Coro(f'{my_bucket}/{path_to_hdf5_file}', s3driver.S3Driver,
                     credentials=s3_creds)

# list group call
all_values = h5obj.listGroup('gt1l/heights', w_attr=True, w_inspect=True)
```
### Output
After running `print(all_values.keys())` notice that the keys include both `Description`, an attribute, and `h_ph`, a variable.
```python
dict_keys(['Description', 'data_rate', 'quality_ph', 'pce_mframe_cnt', 'dist_ph_across', 'h_ph', 'lon_ph', 'ph_id_count', 'delta_time', 'ph_id_pulse', 'dist_ph_along', 'ph_id_channel', 'lat_ph', 'weight_ph', 'signal_conf_ph'])
```
## One potential alternative
When using `listGroup` with `w_inspect=False` the return value is a tuple, such that the user can easily create unique variables for attributes and variables. Mirroring this flow is one alternate solution.
For example:
```python
var_attrs, toplevel_attrs = h5obj.listGroup('gt1l/heights', w_attr=True, w_inspect=False)
```

**Comment by rwegener2** [comment]
I'm actually looking again at:
```python
var_attrs, toplevel_attrs = h5obj.listGroup('gt1l/heights', w_attr=True, w_inspect=False)
```
And it looks like `var_attrs` and `toplevel_attrs` are both returning the same set of keys. Maybe that is the core of a bug hiding somewhere? 🐞😮

**Comment by jpswinski** [comment]
Per the commit above, this has been fixed as recommended.  

Below is an example of ***listGroup*** with `w_inspect=True`.  The variables are returned as a dictionary of dictionaries for each variable listed.  The attributes are a dictionary of values.
```Python
variables, attributes = h5obj.listGroup(args.group, w_attr=True, w_inspect=True)
for variable, listing in variables.items():
    print(f'{variable}:')
    for key, value in listing.items():
        print(f'  {key}: {value}')
for attribute, value in attributes.items():
    print(f'[a] {attribute}: {value}')
```

Below is an example of ***listGroup*** with `w_inspect=False`.  Both the variables and the attributes are a set of strings.
```Python
variables, attributes = h5obj.listGroup(args.group, w_attr=True, w_inspect=False)
for variable in variables:
    print(f'{variable}')
for attribute in attributes:
    print(f'[a] {attribute}')
```
