### ISSUE TITLE
h5coro as an xarray backend

### ISSUE THREAD

**Issue by rwegener2** [ICESat2-SlideRule/h5coro#3]
## Summary

The purpose of this issue is to organize the development of the functionality to use h5coro as an xarray backend. Development work is taking place on the [`backends` branch](https://github.com/ICESat2-SlideRule/h5coro/tree/backends).

## Goal

The end goal of this effort is to have functionality available that mirrors the existing xarray functionality for reading hdf5 data, but is limited to 1D data. That means that, when given a url and a group, the library would read the attributes and data arrays within in that group. It would not traverse down the tree to groups below that group.

### Within the backend class
- [x] organize hackweek atl03 mvp into the h5coro library
- [ ] parse delta_time from an integer to a np.datetime64
- [ ] generalize filename parsing to accept cloud or local filepaths
- [x] propagate attributes from each variable
- [x] propagate attributes from the specified group
- [x] programmatically remove variables with >1 dimension and raise warning
- [x] programmatically set coordinates

### Within the main h5coro code
- [x] create an inspectVariable method that returns the metadata and attributes of a variable
- [x] ability to access the coordinates and dimensionality of a particular variable

## Open questions / Topics for investigation

- Is it true that any user that wants to use this backend will need to set up a local install of xarray? It seems like they need to set the `setup.cfg`, which to me implies they will have to run a local install.

**Comment by jpswinski** [comment]
#### np.datetime64
On SlideRule, to get the data into a value that can be easily converted to an *np.datetime64* we convert the `delta_time` values into the number of nanoseconds since the unix epoch without any leap seconds.  Roughly, the steps are:
`secs_since_gps_epoch` = `delta_time` + ATLAS_SDP_EPOCH_GPS
`num_leap_seconds` = get_leap_seconds( `secs_since_gps_epoch`)
`secs_since_unix_epoch` = `secs_since_gps_epoch` + UNIX_TO_GPS_SECS - `num_leap_seconds`
`ns_since_unix_epoch` = `secs_since_unix_epoch` * 1000000000.0

If this is helpful, let me know and I can provide the constant values we use above to convert between the different epochs.  The trickiest part will be the leap seconds... we have internal libraries to handle leap seconds that we've used for years, so that is what we use, but hopefully there is something easy in Python that does it for you.

**Comment by jpswinski** [comment]
#### access the coordinates and dimensionality 
With the `inspectVariable` method you can get the coordinates and the dimensionality.  They can be accessed like so:
```
metadata, attributes = h5obj.inspectVariable('path_to_var', w_attr=True)
print("dimensions:", metadata.dimensions)
print("coordinates:", attributes['path_to_var' + '/coordinates'].values)
```

**Comment by weiji14** [comment]
> The trickiest part will be the leap seconds.

If it helps, there hasn't been any leap seconds from Jan 2017 - Aug 2023 so far according to https://en.wikipedia.org/wiki/Leap_second, and ICESat-2 was launched on Sep 2018, so this could be left out in the initial implementation.

**Comment by jpswinski** [comment]
@rwegener2 I've created a draft pull request (https://github.com/ICESat2-SlideRule/h5coro/pull/5) with some enhancements to the h5coro internals.  Specifically, I now support a full deep inspection of a group in the `listGroup` function using the `w_inspect` argument.  I don't want to break your existing development with the backend, but I did want to give you a preview of what was coming in case it would be helpful.

**Comment by tsutterley** [comment]
I have [code](https://pytmd.readthedocs.io/en/latest/api_reference/time.html#pyTMD.time.get_leap_seconds) that handles leap seconds using the [NIST tables](https://www.ietf.org/timezones/data/leap-seconds.list). I could rip it out and make it standalone if that is helpful.

**Comment by tsutterley** [comment]
If it is useful, there's a pypi/conda package now called `timescale` that lets you do some conversions. Should allow you to add some parsing. This :point_down: would output a `datetime` array from ATL03 `delta_times` including the addition of leap seconds (which as @weiji14 mentioned is just 0 currently). 
```
import h5py
import timescale

fileID = h5py.File('ATL03_20181014000347_02350101_006_02.h5')
delta_time = fileID['gt1r']['heights']['delta_time'][:]
units = fileID['gt1r']['heights']['delta_time'].attrs['units'].decode('utf-8')
epoch, scale = timescale.time.parse_date_string(units)
dt = timescale.time.Timescale().from_deltatime(scale*delta_time, epoch=epoch, standard='GPS').to_datetime()
```
